# Category Filter on eBay

In [16]:
rootpath = "../Data/"

In [17]:
import pandas as pd

In [18]:
item_features = pd.read_csv(rootpath + 'item_properties_part1.csv')

In [19]:
item_features

              timestamp  itemid    property                            value
0         1435460400000  460429  categoryid                             1338
1         1441508400000  206783         888          1116713 960601 n277.200
2         1439089200000  395014         400  n552.000 639502 n720.000 424566
3         1431226800000   59481         790                       n15360.000
4         1431831600000  156781         917                           828513
...                 ...     ...         ...                              ...
10999994  1439694000000   86599  categoryid                              618
10999995  1435460400000  153032        1066                 n1020.000 424566
10999996  1440298800000  421788         888               35975 856003 37346
10999997  1437879600000  159792         400  n552.000 639502 n720.000 424566
10999998  1436065200000  464846         790                      n410640.000

[10999999 rows x 4 columns]

In [20]:
item_category1 = item_features.loc[item_features.property == 'categoryid', ['itemid', 'value']]

In [21]:
item_category1

          itemid value
0         460429  1338
140       281245  1277
151        35575  1059
189         8313  1147
197        55102    47
...          ...   ...
10999880  441523  1167
10999917  250848   769
10999932  116380  1509
10999960   84186   209
10999994   86599   618

[426305 rows x 2 columns]

In [22]:
item_features = pd.read_csv(rootpath + 'item_properties_part2.csv')

In [23]:
item_category2 = item_features.loc[item_features.property == 'categoryid', ['itemid', 'value']]

In [24]:
item_category = pd.concat([item_category1, item_category2], axis=0)

In [25]:
item_category.groupby('value').count().sort_values('itemid', ascending=False)

       itemid
value
1147    26890
546     24885
1613    21126
491     19998
1404    18217
...       ...
1459        1
776         1
17          1
1152        1
1296        1

[1242 rows x 1 columns]

In [26]:
item_category[item_category.value == '10']

         itemid value
5195834  245380    10
6306471  449019    10
3930791   26377    10
5248943   96493    10

In [27]:
events = pd.read_csv(rootpath + 'events.csv')
events

             timestamp  visitorid event  itemid  transactionid
0        1433221332117     257597  view  355908            NaN
1        1433224214164     992329  view  248676            NaN
2        1433221999827     111016  view  318965            NaN
3        1433221955914     483717  view  253185            NaN
4        1433221337106     951259  view  367447            NaN
...                ...        ...   ...     ...            ...
2756096  1438398785939     591435  view  261427            NaN
2756097  1438399813142     762376  view  115946            NaN
2756098  1438397820527    1251746  view   78144            NaN
2756099  1438398530703    1184451  view  283392            NaN
2756100  1438400163914     199536  view  152913            NaN

[2756101 rows x 5 columns]

In [28]:
events["event"].unique()

array(['view', 'addtocart', 'transaction'], dtype=object)

In [29]:
events["event"].value_counts()

event
view           2664312
addtocart        69332
transaction      22457
Name: count, dtype: int64

In [30]:
events[events.transactionid.notnull()].visitorid.unique().size

11719

In [31]:
events[events.transactionid.notnull()].itemid.unique().size

12025

In [32]:
user_item = events[events.transactionid.notnull()][['visitorid', 'itemid']]

In [33]:
user_item

         visitorid  itemid
130         599528  356475
304         121688   15335
418         552148   81345
814         102019  150318
843         189384  310791
...            ...     ...
2755294    1050575   31640
2755349     861299  456602
2755508     855941  235771
2755603     548772   29167
2755607    1051054  312728

[22457 rows x 2 columns]

In [34]:
user_item_category = pd.merge(left = user_item , right = item_category, how = "inner", on = "itemid")
user_item_category['purchase'] = 1

In [35]:
user_item_category

       visitorid  itemid value  purchase
0         599528  356475   386         1
1         121688   15335  1098         1
2         552148   81345  1393         1
3         102019  150318  1236         1
4         189384  310791   437         1
...          ...     ...   ...       ...
43647    1050575   31640     5         1
43648     861299  456602  1173         1
43649     855941  235771  1173         1
43650     548772   29167  1192         1
43651    1051054  312728  1098         1

[43652 rows x 4 columns]

In [36]:
user_item_category.value.unique().size

751

In [37]:
user_item_category.visitorid.unique().size

11569

In [38]:
user_category_matrix = user_item_category.pivot_table(values='purchase', index='visitorid', columns='value', fill_value=0)

In [39]:
user_category_matrix.sum().sum()

19371.0

In [40]:
user_category_matrix.shape

(11569, 751)

In [41]:
user_category_matrix

value,0,1,1001,1002,1003,1006,1011,1013,1014,1017,...,979,983,984,985,987,988,992,997,998,999
visitorid,,,,,,,,,,,,,,,,,,,,,
172,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
186,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
264,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
419,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
539,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1406787,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1406981,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1407070,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1407110,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1407398,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [42]:
from sklearn.decomposition import NMF

In [43]:
nmf_model = NMF(n_components=32)

nmf_model.fit(user_category_matrix)

NMF(n_components=32)

In [44]:
user_embedding = nmf_model.transform(user_category_matrix)
category_embedding = nmf_model.components_.T

In [45]:
user_embedding[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.22574334, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.19842596, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [46]:
category_embedding.shape

(751, 32)

In [47]:
import numpy as np

In [48]:
np.save(rootpath + 'category_embedding.npy', category_embedding)

In [49]:
similarities = np.matmul(category_embedding, category_embedding.T)

In [50]:
user_category_matrix.columns

Index(['0', '1', '1001', '1002', '1003', '1006', '1011', '1013', '1014',
       '1017',
       ...
       '979', '983', '984', '985', '987', '988', '992', '997', '998', '999'],
      dtype='object', name='value', length=751)

In [51]:
simlarity_matrix = pd.DataFrame(similarities, index=user_category_matrix.columns, columns=user_category_matrix.columns)

In [52]:
simlarity_matrix > 0.01

value,0,1,1001,1002,1003,1006,1011,1013,1014,1017,...,979,983,984,985,987,988,992,997,998,999
value,,,,,,,,,,,,,,,,,,,,,
0,True,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,True,True,False,False,False,...,False,False,True,False,False,False,False,False,False,False
1001,False,False,False,False,False,True,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
1002,False,False,False,True,False,True,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
1003,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,False,False,False,False,False,True,False,False,False,False,...,False,False,True,False,True,True,False,False,False,False
992,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
999,False,False,False,False,False,True,False,False,False,False,...,True,False,False,False,False,False,False,False,False,True

In [53]:
boolean_similarity = simlarity_matrix > 0.01

In [54]:
boolean_similarity['0'][boolean_similarity['0']]

value
0       True
1011    True
1037    True
1082    True
1114    True
1247    True
1277    True
1286    True
133     True
1366    True
1373    True
1375    True
1384    True
1404    True
1493    True
1555    True
1634    True
228     True
242     True
302     True
356     True
366     True
381     True
429     True
434     True
579     True
646     True
694     True
707     True
715     True
769     True
808     True
816     True
847     True
858     True
921     True
936     True
Name: 0, dtype: bool